name: essential_flutter
description: Flutter widgets, components, and services building on essential_dart for accelerated UI development.
version: 1.1.0
repository: https://github.com/maranix/essential
issue_tracker: https://github.com/maranix/essential/issues

environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

resolution: workspace

topics:
  - widgets
  - ui
  - architecture
  - flutter

dependencies:
  essential_dart: any
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.35.0

flutter:
