name: essential_dart
description: Reusable building blocks, patterns, and services for Dart to improve efficiency and code quality.
version: 2.0.0
repository: https://github.com/maranix/essential/tree/main/packages/essential_dart
issue_tracker: https://github.com/maranix/essential/issues?q=state%3Aopen%20label%3Adart

environment:
  sdk: ^3.10.1

resolution: workspace

topics:
  - utilities
  - patterns
  - architecture
  - efficiency

# Add regular dependencies here.
dependencies:
  async: ^2.13.0

dev_dependencies:
  pedantic_mono: ^1.35.0
  test: ^1.25.6
