name: essential_dart
description: Reusable building blocks, patterns, and services for Dart to improve efficiency and code quality.
version: 1.0.0
repository: https://github.com/maranix/essential
issue_tracker: https://github.com/maranix/essential/issues

environment:
  sdk: ^3.10.1

resolution: workspace

topics:
  - utilities
  - patterns
  - architecture
  - efficiency

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
